### 0-1. 자산연동 OAuth 2.0: 인가코드 발급 요청 (GET)
GET http://localhost:9090/v2/oauth/2.0/authorize?response_type=code&client_id=Shinvia_client_id&redirect_uri=https://oauth.pstmn.io/v1/callback&org_code=ShinVia&state=xyz123&app_scheme=shinvia://oauth
x-user-ci: 1
x-api-tran-id: MOCK_TRAN_100000001

### 0-2. 자산연동 OAuth 2.0: 토큰 발급 요청 (POST)
POST http://localhost:9090/v2/oauth/2.0/token
Content-Type: application/x-www-form-urlencoded
x-api-tran-id: MOCK_TRAN_100000002

grant_type=authorization_code&code=MOCK_CODE_REPLACE_WITH_CODE&client_id=Shinvia_client_id&org_code=ShinVia&redirect_uri=https://oauth.pstmn.io/v1/callback

### 1-1. 카드 목록 조회 (ci = 1, 신비아)
GET http://localhost:9090/v2.0/cards?bank_tran_id=T1001&ci=1&bank_code_std=004&member_bank_code=004
Authorization: Bearer test-token

### 1-2. 카드 목록 조회 (ci = 2, 신신비비)
GET http://localhost:9090/v2.0/cards?bank_tran_id=T1001&ci=2&bank_code_std=004&member_bank_code=004
Authorization: Bearer test-token

### 1-3. 카드 청구정보/거래내역 조회 (ci = 1, 신비아)
GET http://localhost:9090/v2.0/cards/bills?bank_tran_id=T1002&ci=1&bank_code_std=004&member_bank_code=004&from_month=202506&to_month=202507
Authorization: Bearer test-token

### 1-4. 카드 청구정보/거래내역 조회 (ci = 2, 신신비비)
GET http://localhost:9090/v2.0/cards/bills?bank_tran_id=T1002&ci=2&bank_code_std=004&member_bank_code=004&from_month=202506&to_month=202507
Authorization: Bearer test-token

### 2-1. 계좌 잔액조회
GET http://localhost:9090/v2.0/account/balance/fin_num?bank_tran_id=T1003&fintech_use_num=123456789012345678901234&bank_code_std=004
Authorization: Bearer test-token

### 2-2. 계좌 거래내역조회 (일자 단위)
GET http://localhost:9090/v2.0/account/transaction_list/fin_num?bank_tran_id=T1004&fintech_use_num=123456789012345678901234&inquiry_type=A&inquiry_base=D&from_date=20250601&to_date=20250731&sort_order=D&tran_dtime=20260730140000
Authorization: Bearer test-token

### 2-3. 계좌 거래내역조회 (시간 단위)
GET http://localhost:9090/v2.0/account/transaction_list/fin_num?bank_tran_id=T1004b&fintech_use_num=123456789012345678901234&inquiry_type=A&inquiry_base=T&from_date=20250705&from_time=140000&to_date=20250705&to_time=150000&sort_order=A&tran_dtime=20260730140000
Authorization: Bearer test-token
